### ISSUE TITLE
Is mac osx supported

### ISSUE THREAD

**Issue by ruotianluo** [marufshidiq/gdrive-cli-builder#6]
If not, how to make it support?

**Comment by marufshidiq** [comment]
I think it's can work in osx, you can try to build with this option
- darwin/386
- darwin/amd64
- darwin/arm
- darwin/arm64

**Comment by ruotianluo** [comment]
Thanks

**Comment by marufshidiq** [comment]
Is it work for your mac? Because i don't have any apple product to try

**Comment by ruotianluo** [comment]
It works.

**Comment by marufshidiq** [comment]
Great, so i can close this issue
